# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7a8574e0caf97cb2e1fb9b0d83405191a76b04a81650533c94d908e70621554d020c7e7bcd26e773a0fc5bfc88b03674c5af9bcd24958675b478c3fc398b5cb

test:
  secret_key_base: 2d395824153773ca344c21f0c88f2f754fd59d13cb357dd6799a2cf0863e41069ef56cba111766762be7cd417d90cd468360c2848c593e99ab2e0b041f36ee90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
